export enum CalendarStopReason {
  TARGET_REACHED = 'TARGET_REACHED',
  MATCH_DAY = 'MATCH_DAY',
  BLOCKING_EVENT = 'BLOCKING_EVENT',
  TRANSFER_WINDOW_BOUNDARY = 'TRANSFER_WINDOW_BOUNDARY',
  SEASON_BOUNDARY = 'SEASON_BOUNDARY',
  MANAGER_DISMISSED = 'MANAGER_DISMISSED',
}
