/** Prototype tuning, not claimed to reproduce any real club's employment policy. */
export const MANAGER_CAREER_CONFIG = {
  initialFanApproval: 65,
  initialBoardConfidence: 65,
  minimumWinChance: 0.15,
  maximumWinChance: 0.85,
  abilityDifferenceForMaximumAdvantage: 28,
  fanResultWeight: 8,
  boardResultWeight: 5,
  fanStreakStartsAt: 3,
  fanMaximumStreakEffect: 3,
  boardStreakStartsAt: 4,
  boardMaximumStreakEffect: 2,
  minimumSeriesForWarning: 6,
  warningGraceSeries: 3,
  poorResultMaximumWinRate: 0.35,
  poorResultExpectedWinsDeficit: 1.5,
  poorResultLosingStreak: 6,
  warningFanApproval: 40,
  warningBoardConfidence: 50,
  dismissalFanApproval: 25,
  dismissalBoardConfidence: 35,
  recoveryWinningStreak: 2,
  recoveryFanApproval: 45,
  recoveryBoardConfidence: 55,
  splitMaximumFanEffect: 12,
  splitMaximumBoardEffect: 8,
  transferFanEffectPerAbility: 0.2,
  transferBoardEffectPerAbility: 0.15,
  transferMaximumFanEffect: 3,
  transferMaximumBoardEffect: 2,
} as const;
