import { PlayerPersonality } from '../../players/enums/player-personality.enum';

// Prototype economic balance; all monetary amounts are annual salaries in 만원.
export const CONTRACT_CONFIG = {
  maxNegotiationRounds: 5,
  decisionExtensionDays: 2,
  maxDecisionExtensions: 1,
  limits: {
    minAnnualSalary: 1,
    maxAnnualSalary: 10_000_000,
    minYears: 1,
    maxYears: 5,
    maxPromises: 8,
  },
  responseDelay: { minDays: 1, maxDays: 3 },
  negotiation: {
    salaryBase: 1_000,
    salaryPerAbilitySquared: 15,
    salaryRounding: 100,
    currentSalaryFloorRatio: 1,
    salaryAcceptanceRatio: 0.95,
    maxSalaryBenefit: 1.35,
    moneyWeight: 35,
    nonMoneyBase: 25,
    trustNeutral: 50,
    trustWeight: 0.3,
    teamStrengthWeight: 0.2,
    starterBonus: 7,
    coreBonus: 5,
    planBonus: 4,
    acceptScore: 60,
    starAbility: 85,
    carryDemandAbility: 75,
    teamStrengthGap: 12,
    maxComfortableYears: 3,
    additionalYearSalaryRatio: 0.08,
    trustSalaryAdjustment: 0.003,
    teamSalaryAdjustment: 0.002,
    planSalaryDiscount: 0.04,
    lowTrustRejection: {
      [PlayerPersonality.DEVOTED]: 10,
      [PlayerPersonality.LOYAL]: 25,
      [PlayerPersonality.SELF_CENTERED]: 15,
      [PlayerPersonality.PROFESSIONAL]: 10,
      [PlayerPersonality.SENSITIVE]: 20,
    },
    personalitySalaryRatio: {
      [PlayerPersonality.DEVOTED]: 0.92,
      [PlayerPersonality.LOYAL]: 0.95,
      [PlayerPersonality.SELF_CENTERED]: 1.12,
      [PlayerPersonality.PROFESSIONAL]: 1,
      [PlayerPersonality.SENSITIVE]: 1.02,
    },
  },
} as const;
