export enum TeamStrategy {
  BALANCED = 'BALANCED',
  TOP_CARRY = 'TOP_CARRY',
  TOP_JUNGLE = 'TOP_JUNGLE',
  MID_CARRY = 'MID_CARRY',
  MID_JUNGLE = 'MID_JUNGLE',
  UPPER_SIDE = 'UPPER_SIDE',
  BOT_CARRY = 'BOT_CARRY',
  BOT_PRESSURE = 'BOT_PRESSURE',
}
