export const MATCH_STATS_CONFIG = {
  derivedSeedXor: 0xa5a5_a5a5,
  durationMinutes: { min: 25, max: 40 },
  winnerKills: { min: 12, max: 22 },
  loserKills: { min: 6, max: 18 },
  allocationRandomMultiplier: { min: 0.75, max: 1.25 },
  killWeightFloor: 10,
  deathWeightFloor: 10,
  participationRate: { min: 0.5, max: 0.9 },
  dpm: {
    base: 250,
    mechanicsMultiplier: 3,
    teamFightMultiplier: 2,
    randomMin: -60,
    randomMax: 60,
    minimum: 100,
  },
  goldPerMinute: {
    base: 250,
    laningMultiplier: 1,
    mechanicsMultiplier: 0.5,
    randomMin: -20,
    randomMax: 20,
    minimum: 150,
  },
  laneDifference: {
    goldPerLaningPoint: 20,
    goldRandomMin: -150,
    goldRandomMax: 150,
    csPerLaningPoint: 0.3,
    csRandomMin: -5,
    csRandomMax: 5,
  },
  rating: {
    base: 5,
    kdaBaseline: 3,
    kdaMultiplier: 0.4,
    dpmBaseline: 500,
    dpmDivisor: 200,
    gdAt15Divisor: 1000,
    kpBaseline: 60,
    kpDivisor: 40,
    winnerBonus: 0.3,
    min: 0,
    max: 10,
  },
  displayedDecimalPlaces: 3,
} as const;
