export enum CalendarEventType {
  SCHEDULED_GAME = 'SCHEDULED_GAME',
  CONTRACT_RESPONSE = 'CONTRACT_RESPONSE',
  LEGEND_REVEAL = 'LEGEND_REVEAL',
  PLAYER_MEETING = 'PLAYER_MEETING',
  INTERNATIONAL_ROSTER_REGISTRATION = 'INTERNATIONAL_ROSTER_REGISTRATION',
  SEASON_REVIEW = 'SEASON_REVIEW',
  TRANSFER_WINDOW_OPEN = 'TRANSFER_WINDOW_OPEN',
}
