export enum LeagueStageFormat {
  ROUND_ROBIN = 'ROUND_ROBIN',
  GROUP = 'GROUP',
  SWISS = 'SWISS',
  PLAY_IN = 'PLAY_IN',
  SINGLE_ELIMINATION = 'SINGLE_ELIMINATION',
  DOUBLE_ELIMINATION = 'DOUBLE_ELIMINATION',
  GAUNTLET = 'GAUNTLET',
}
